#!/usr/bin/env python
"""Generate one shard of the SIMORGH simulation grid. One SLURM array task.

    python scripts/fir/simulate_shard.py --grid-dir ~/scratch/simorgh/grids/v1 \
        --index $SLURM_ARRAY_TASK_ID

Idempotent: an existing, hash-matching shard is skipped, so a partially
failed array can simply be resubmitted whole.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from simorgh.simulate.grid import generate_shard, read_grid_meta  # noqa: E402


def build_simulator(meta: dict):
    """Construct the simulator named in the grid metadata.

    The grid records which forward model it was generated with; this
    refuses to run if that record does not match what is installed,
    because a grid half-generated by two different simulators would train
    a network with no consistent meaning.
    """
    kind = meta["simulator"].get("engine")
    if kind == "toy":
        from simorgh.simulate.toy import ToySubNeptune
        return ToySubNeptune()
    if kind == "taurex3":
        from simorgh.simulate.taurex_adapter import TaurexSubNeptune
        sim = TaurexSubNeptune(
            opacity_path=meta["simulator"]["opacity_path"],
            cia_path=meta["simulator"]["cia_path"],
            star_radius_rsun=meta["simulator"].get("star_radius_rsun", 0.45),
            nlayers=meta["simulator"].get("nlayers", 100))
        if sim.provenance_hash != meta["simulator"].get("provenance_hash"):
            raise RuntimeError(
                "TauREx provenance hash does not match the grid metadata: "
                f"{sim.provenance_hash} != "
                f"{meta['simulator'].get('provenance_hash')}. The opacity "
                "paths or model settings changed since the grid was defined.")
        return sim
    raise ValueError(f"unknown simulator engine: {kind!r}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--grid-dir", required=True)
    ap.add_argument("--index", type=int, required=True)
    ap.add_argument("--overwrite", action="store_true")
    args = ap.parse_args()

    grid_dir = Path(args.grid_dir).expanduser()
    meta = read_grid_meta(grid_dir)
    sim = build_simulator(meta)

    t0 = time.time()
    out = generate_shard(grid_dir, args.index, sim, overwrite=args.overwrite)
    n = meta["sims_per_shard"]
    dt = time.time() - t0
    print(f"shard {args.index:5d}: {n} sims -> {out.name}  "
          f"{dt:.1f}s ({dt / max(n, 1) * 1e3:.1f} ms/sim)", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
